CREATE TABLE "SEQUENCE"
(
    "SEQ_KEY"       VARCHAR2(255) PRIMARY KEY NOT NULL,
    "SEQ_VALUE"     NUMBER(20) DEFAULT 0      NOT NULL,
    "SEQ_INCREMENT" NUMBER(11) DEFAULT 1      NOT NULL,
    "SEQ_CACHE"     NUMBER(11) DEFAULT 10000  NOT NULL,
    "SEQ_VERSION"   NUMBER(11) DEFAULT 1      NOT NULL
);
COMMENT ON TABLE "SEQUENCE" IS 'SEQUENCE';
COMMENT ON COLUMN "SEQUENCE"."SEQ_KEY" IS 'KEY';
COMMENT ON COLUMN "SEQUENCE"."SEQ_VALUE" IS 'VALUE';
COMMENT ON COLUMN "SEQUENCE"."SEQ_INCREMENT" IS 'INCREMENT';
COMMENT ON COLUMN "SEQUENCE"."SEQ_CACHE" IS 'CACHE SIZE';
COMMENT ON COLUMN "SEQUENCE"."SEQ_VERSION" IS 'VERSION';